version: '3'
services:
  web:
    image: ${APP_IMAGE_HOST}:latest
    restart: unless-stopped
    ports:
      - 20040:80
    volumes:
      - ./log:/app/log
      - ./tmp:/app/tmp
      #   暴露备份文件给js调用
      # - production/db/mongoBackups:/dbData/backups
    environment:
      APP_PORT: 80
      # APP_MAILER_FROM: ''
      # APP_MAILER_SMTP_ADDRESS: ''
      # APP_MAILER_SMTP_PORT: 465
      # APP_MAILER_SMTP_USERNAME: ''
      # APP_MAILER_SMTP_PASSWORD: ''
      APP_MONGO: mongodb://mongo:27017/app
      APP_REDIS_MASTER: redis://redis:6379/0
      APP_SECRET_KEY_BASE: ''
      # APP_SESSION_KEY: ${APP_SESSION_KEY}
      # APP_SESSION_DOMAIN: ${APP_SESSION_DOMAIN}
      NODE_ENV: production
    container_name: com.pigpen.prod
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 20041:27017
    container_name: com.pigpen.mongo
    volumes:
      # 按需要暴露数据库文件
      - ./mongoData:/data/db
      # 暴露备份文件方便发送备份数据
      - ./mongoBackups:/data/backups
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379
    container_name: com.pigpen.redis
